package com.kaneki.aicoder.ui.theme

import androidx.compose.ui.graphics.Color

// Fallback seed palette (Material 3 tonal) — dipakai di API < 31
// saat dynamic color / Monet tidak tersedia.

val md_theme_light_primary = Color(0xFF39693B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBAF0B6)
val md_theme_light_onPrimaryContainer = Color(0xFF215025)
val md_theme_light_secondary = Color(0xFF516350)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD4E8D0)
val md_theme_light_onSecondaryContainer = Color(0xFF3A4B3A)
val md_theme_light_tertiary = Color(0xFF39656C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBDEAF2)
val md_theme_light_onTertiaryContainer = Color(0xFF1F4D53)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF7FBF2)
val md_theme_light_onBackground = Color(0xFF181D17)
val md_theme_light_surface = Color(0xFFF7FBF2)
val md_theme_light_onSurface = Color(0xFF181D17)
val md_theme_light_surfaceVariant = Color(0xFFDEE5D8)
val md_theme_light_onSurfaceVariant = Color(0xFF424940)
val md_theme_light_outline = Color(0xFF72796F)
val md_theme_light_outlineVariant = Color(0xFFC2C9BD)

val md_theme_dark_primary = Color(0xFF9FD49C)
val md_theme_dark_onPrimary = Color(0xFF053911)
val md_theme_dark_primaryContainer = Color(0xFF215025)
val md_theme_dark_onPrimaryContainer = Color(0xFFBAF0B6)
val md_theme_dark_secondary = Color(0xFFB8CCB5)
val md_theme_dark_onSecondary = Color(0xFF243424)
val md_theme_dark_secondaryContainer = Color(0xFF3A4B3A)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4E8D0)
val md_theme_dark_tertiary = Color(0xFFA1CED6)
val md_theme_dark_onTertiary = Color(0xFF00363C)
val md_theme_dark_tertiaryContainer = Color(0xFF1F4D53)
val md_theme_dark_onTertiaryContainer = Color(0xFFBDEAF2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF10140F)
val md_theme_dark_onBackground = Color(0xFFE0E4DB)
val md_theme_dark_surface = Color(0xFF10140F)
val md_theme_dark_onSurface = Color(0xFFE0E4DB)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C9BD)
val md_theme_dark_outline = Color(0xFF8C9388)
val md_theme_dark_outlineVariant = Color(0xFF424940)
